name: Laravel Pint

on:
  push:
    branches:
      - main

jobs:
  laravel-pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{github.head_ref}}

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          tools: composer:v2

      - name: Install Laravel Pint
        run: composer global require laravel/pint

      - name: Run Pint
        run: pint

      - name: Push changes if exist to repo
        run: |
          git config user.name "Muhammad_Nawlo"
          git config user.email "nawlomuhammadit@gmail.com"
          git add .
          git commit -m "laravel pint" || exit 0
          git push